### PR TITLE
Added heater driver

### PR DESCRIPTION
**Pull request by RonnyWinkler**
Added heater driver
Added capability thermostat_heater_mode
Added heater case in app.js getTypeDriver(type)

### CODE REVIEW

**Comment by RonnyWinkler** [comment]
This PR ist still in work...

**Comment by jurgenheine** [comment]
Changes looking nice:) Can you make a PR to devellop branch instead of master?. Code will be merged to test when version is published to test and will be merged to master when version is published for public.

**Comment by RonnyWinkler** [comment]
It is not possible to change the PR, right? I have to create a new one?

**Comment by jurgenheine** [comment]
To be honest, I don't know. 

Found also some documentation about your device:
Instruction set: https://developer.tuya.com/en/docs/iot/f?id=K9gf46epy4j82
Status set: https://developer.tuya.com/en/docs/iot/s?id=K9gf48r1eqi4s_

**Comment by RonnyWinkler** [comment]
I can see all functions and status values in the debug page:
grafik

But I can't find something about a DP ID "Gear".
grafik

For me it seems that is not heater dependent state. Perhaps there are general settings used in another API...

**Pull request closed without merging**
