### PR TITLE
Tuyagaragedooropener

### PR DESCRIPTION
**Pull request by maccyber**
Thanks for the awesome work @jurgenheine 
This adds support for Tuya Garage Door Opener (i.e. https://www.aliexpress.com/item/4000903671119.html) LoraTap Tuya Smart Life Garage Door Sensors Opener Controller WiFi Switch.

`alarm_contact` and `garagedoor_closed` capabilities is added.

### CODE REVIEW

**Comment by jurgenheine** [comment]
Good job, I merged the PR's and will try to create new build

**Comment by jurgenheine** [comment]
New build is published to test

**Comment by maccyber** [comment]
Thanks for the quick feedback.
Installed https://homey.app/no-no/app/com.tuya.cloud/Tuya-cloud/test/

I tested the new version with tuya producs:
- 2 x contact sensors
- 1 x socket
- 1 x smart garage door opener

Everything seemed to work as excpected

**Comment by jurgenheine** [comment]
It is looking nice. I will keep it in test for 1 week, after that I will push it to general. Please do remind me if I forgot it

**Comment by maccyber** [comment]
Willy do. Thanks

**Pull request merged**
